### ISSUE TITLE
[BUG] Cannot build the cli tool with either docker or using pip

### ISSUE THREAD

**Issue by opoei** [wirepas/backend-client#138]
I've tried all three tagged commits and the latest from master.

Attempting to build the wheel file gives me mysql dependency errors:
```
Collecting mysqlclient>=1.3.13 (from wirepas-backend-client==1.1.0)
  Using cached https://files.pythonhosted.org/packages/4d/38/c5f8bac9c50f3042c8f05615f84206f77f03db79781db841898fde1bb284/mysqlclient-1.4.4.tar.gz
    Complete output from command python setup.py egg_info:
    /bin/sh: mysql_config: command not found
    /bin/sh: mariadb_config: command not found
    /bin/sh: mysql_config: command not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/tr/d8jpqvcs1wn_vl_yj94wmwb80000gn/T/pip-install-k8gv61y2/mysqlclient/setup.py", line 16, in <module>
        metadata, options = get_config()
      File "/private/var/folders/tr/d8jpqvcs1wn_vl_yj94wmwb80000gn/T/pip-install-k8gv61y2/mysqlclient/setup_posix.py", line 61, in get_config
        libs = mysql_config("libs")
      File "/private/var/folders/tr/d8jpqvcs1wn_vl_yj94wmwb80000gn/T/pip-install-k8gv61y2/mysqlclient/setup_posix.py", line 29, in mysql_config
        raise EnvironmentError("%s not found" % (_mysql_config_path,))
    OSError: mysql_config not found

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/tr/d8jpqvcs1wn_vl_yj94wmwb80000gn/T/pip-install-k8gv61y2/mysqlclient/
```
Trying to run the cli tool in the command line has an issue with the volume: 
```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:345: starting container process caused "process_linux.go:430: container init caused \"rootfs_linux.go:58: mounting \\\"/Users/oliver/Downloads/Wirepas/backend-client/settings.yml\\\" to rootfs \\\"/var/lib/docker/overlay2/382d0c9d0c1678d87333bce49d75e59def5fc57f6f0d3d4bcd42615011570e99/merged\\\" at \\\"/var/lib/docker/overlay2/382d0c9d0c1678d87333bce49d75e59def5fc57f6f0d3d4bcd42615011570e99/merged/home/wirepas/vars/settings.yml\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type.
```

If I create a settings directory and try to volume mount that `$(pwd)/settings:/home/wirepas/vars the cli tool is not configured.`

Trying to install with pip gives:
```
 pip3 install wirepas-backend-client
Collecting wirepas-backend-client
  Using cached https://files.pythonhosted.org/packages/71/b0/53951e6c800b6a129f49c53feb266ee215cbe7a0d9d4234ea4c3bba48e5b/wirepas_backend_client-1.1.0-py3-none-any.whl
Collecting mysqlclient>=1.3.13 (from wirepas-backend-client)
  Using cached https://files.pythonhosted.org/packages/4d/38/c5f8bac9c50f3042c8f05615f84206f77f03db79781db841898fde1bb284/mysqlclient-1.4.4.tar.gz
    Complete output from command python setup.py egg_info:
    /bin/sh: mysql_config: command not found
    /bin/sh: mariadb_config: command not found
    /bin/sh: mysql_config: command not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/tr/d8jpqvcs1wn_vl_yj94wmwb80000gn/T/pip-install-_2vlgkgd/mysqlclient/setup.py", line 16, in <module>
        metadata, options = get_config()
      File "/private/var/folders/tr/d8jpqvcs1wn_vl_yj94wmwb80000gn/T/pip-install-_2vlgkgd/mysqlclient/setup_posix.py", line 61, in get_config
        libs = mysql_config("libs")
      File "/private/var/folders/tr/d8jpqvcs1wn_vl_yj94wmwb80000gn/T/pip-install-_2vlgkgd/mysqlclient/setup_posix.py", line 29, in mysql_config
        raise EnvironmentError("%s not found" % (_mysql_config_path,))
    OSError: mysql_config not found
```

**Comment by PFigs** [comment]
Hi!

Thanks for your report!

The host dependencies are listed under 

https://github.com/wirepas/backend-client/blob/master/container/slim/Dockerfile#L13

You'll have to meet those in order to install the package with success. 

Regarding your docker issue, could you share the full command? From the output it seems like an error related to your volume mount.

Could you check what is your host's user and group? If it is not the one stated in the container could you change chown 1000:1000 .settings? 

Do you get the same issue if you use https://github.com/wirepas/backend-client/blob/master/container/docker-compose.yml to run the service? Pay attention that by default we map a dot file (.settings.yml).

Cheers

**Comment by PFigs** [comment]
I've given it a shot on my side and we do lack a bit on the instructions regarding launching this via docker-compose. We'll add prior to the next release (target is 20.09).

To help you, meanwhile do the following:
* copy your settings file or link it to container/.settings.yml (dot and extension are important)
* change the compose file in container/docker-compose.yml to the following

```
version: '2'
services:
    backend-client:
      restart: always
      image: wirepas/backend-client:v1.2.0-rc.3
      build:
        dockerfile: container/slim/Dockerfile
        context: ../
      network_mode: host

      environment:
        - WM_DEBUG_LEVEL=error
        - PYTHONUNBUFFERED=true

      volumes:
        - ./.settings.yml:/home/wirepas/vars/settings.yml

      command: python examples/mqtt_viewer.py --settings /home/wirepas/vars/settings.yml

```
* Pull the image or build it
> docker-compose -f container/docker-compose.yml pull 
> docker-compose -f container/docker-compose.yml build

* Start the command line with
> docker-compose -f container/docker-compose.yml **run** backend-client wm-gw-cli --settings /home/wirepas/vars/settings.yml

Note that from v1.2.0 you can also set environment parameters thus making it possible to set the MQTT credentials right on the compose file under the environment key.

Check how we run smoke tests at: https://github.com/wirepas/backend-client/blob/master/tests/services/docker-compose.yml

**Comment by opoei** [comment]
The latest changes definitely help. However there are still mistakes. 
`- ./.settings.yml:/home/wirepas/vars/settings.yml`
Docker does not do well with relative paths, additionally having the setting.yml as a dotfile seems like poor practice. I changed it to:
`  - $PWD/settings.yml:/home/wirepas/vars/settings.yml` 

The latest image on dockerhub yields the error:
`IsADirectoryError: [Errno 21] Is a directory: '/home/wirepas/vars'`

**Comment by PFigs** [comment]
Hi @opoei ,

Docker compose handles relative paths properly. I don't see a good reason not to use them. However, one needs to keep in mind that their relativity refer to the composition file itself and not from where you start the command. 

For example:

`docker-compose -f container/docker-compose.yml `

Expects the settings file to be available under 

`container/.settings.yml`

We have seen people having trouble with this part as they expect the settings to be in the root of the directory instead. It is certainly something we will have to revisit in the future.

The error is due to your

` $PWD/settings.yml`. 

It  does not seem to exist and docker-compose is happily creating a folder in its place. Thus, you end up mounting a folder and you received the error 21. 

If that is not the case, could you paste the command you are setting in your compose file?

With regards to the use of dotfiles, I have observed it to be a common pattern in other projects. Nevertheless, there are risks with it as it will be hidden in most file systems. However, it is not at all a fixed name since you can specify any file as a target by setting it with --settings. Likewise, you can also use environment keys to set parameters.

What other reasons do you see for considering .setting.yml as poor practice?
